OverFishy/MaDoggo

- Gemfile
- Gemfile.lock
- db/seeds.rb
Added 10 dogs in the seed
Added a park visit in the seed
small style fixes
add platform x86_64-linux, for Heroku computability
> Seed update

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_map.scss
- app/controllers/parks_controller.rb
- app/javascript/controllers/mapbox_controller.js
- app/views/parks/_info_window.html.erb
created the pop up when pressing on a map marker
created a link on the pop up (redirect to parks#index instead of parks#show)
> pop up added

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_map.scss
- app/controllers/parks_controller.rb
- app/javascript/controllers/mapbox_controller.js
- app/models/park.rb
- app/views/dogs/_form.html.erb
- app/views/parks/_info_window.html.erb
- config/environments/development.rb
- config/storage.yml
- db/migrate/20220302104100_create_active_storage_tables.active_storage.rb
- db/schema.rb
added cloudinary, and the option to add a photo to a park
decommented the ability to add photos to your doggo
> Cloudinary

- app/views/parks/_info_window.html.erb
redirected popup to the correct parks#page
> redirected popup

- app/assets/stylesheets/components/_footer.scss
- app/views/shared/_footer.html.erb
changed border radius
changed class name of "active" to "activep"
> footer fixes

- Gemfile
- Gemfile.lock
> improved gemfile files

- app/assets/stylesheets/components/_info_window.scss
- app/controllers/parks_controller.rb
- app/models/park.rb
- app/views/parks/_info_window.html.erb
- db/seeds.rb
> number on the popup

- app/helpers/application_helper.rb
- app/views/dashboards/show.html.erb
- db/migrate/20220303101456_add_name_to_users.rb
- db/schema.rb
- db/seeds.rb
updated seed, 4 realistic users, added name to user, added more friendships and more park visits
> Seed updates

- db/seeds.rb
> Email seedfix

- config/environments/production.rb
> changed env config

- app/assets/stylesheets/components/_footer.scss
- app/views/layouts/application.html.erb
- app/views/parks/index.html.erb
Fixed the display of our map on the map page
> fixed map show page

- app/controllers/park_reviews_controller.rb
- app/models/park_review.rb
- app/views/park_reviews/_review_form.html.erb
- app/views/park_reviews/new.html.erb
- config/routes.rb
-routes and validations done
-parks controller new method done
-parks review for done
-parks new page done
> Park reeview skeleton

- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/parks/_show.scss
- app/views/parks/show.html.erb
finish the buttons for the show page
> finish buttons show page

- app/channels/chatroom_channel.rb
- app/controllers/park_messages_controller.rb
- app/controllers/parks_controller.rb
- app/javascript/controllers/chatroom_subscription_controller.js
- app/views/park_messages/_message.html.erb
- app/views/park_messages/index.html.erb
- app/views/parks/show.html.erb
- config/routes.rb
- test/channels/chatroom_channel_test.rb
- test/controllers/park_messages_controller_test.rb
park chat is up and running, need some touch up on styling
> Park chatroom

- app/assets/stylesheets/components/_dogcard.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/parks/_show.scss
- app/helpers/dog_helper.rb
- app/views/parks/_dog_park.html.erb
- app/views/parks/show.html.erb
finish the dog page 
and the show buttons
> finish dog page

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_park-img.scss
- app/assets/stylesheets/components/_park-review.scss
- app/views/park_reviews/new.html.erb
- app/views/parks/_info_window.html.erb
- app/views/parks/show.html.erb
Completed functionality of parks review page
created each review to appear in a card
polished park show page
> Park reviews page complete

- app/views/parks/_dog.html.erb
- app/views/parks/_dog_park.html.erb
now in cards, the photos match the dog
> swithed photos of dogs

- app/views/parks/show.html.erb
- db/schema.rb
deleted double instances in park show pagee
> minor park show page

- app/assets/stylesheets/parks/_show.scss
added curley brackets ats _show.scss so it won't break the code
> added curley brackets on show.scss

- app/views/shared/_body.html.erb
> added pic to slide

- app/assets/stylesheets/parks/_show.scss
- app/views/park_reviews/new.html.erb
- app/views/parks/_info_window.html.erb
- app/views/parks/show.html.erb
- db/seeds.rb
added 2 dog parks
add default photo for photo less dog parks
> Seed volume

- app/views/park_reviews/new.html.erb
- app/views/parks/show.html.erb
- db/seeds.rb
> Add seed data

- app/assets/stylesheets/components/_body.scss
- app/assets/stylesheets/components/_dashboard.scss
- app/assets/stylesheets/components/_map.scss
- app/assets/stylesheets/components/_park-img.scss
- app/assets/stylesheets/pages/_footer.scss
- app/assets/stylesheets/parks/_show.scss
- app/views/dashboards/show.html.erb
- app/views/parks/_attend_button.html.erb
- app/views/parks/_info_window.html.erb
- app/views/parks/show.html.erb
- app/views/shared/_body.html.erb
* fixed buttons
* fixed texts
* fixed orders, containers, divs
> implemented design fixes

- app/views/park_reviews/new.html.erb
- app/views/parks/show.html.erb
minor changes from park to @park to avoid breaking
> minor changes

- app/assets/stylesheets/components/_body.scss
- app/assets/stylesheets/components/_info_window.scss
- app/assets/stylesheets/components/_park-img.scss
- app/views/parks/_info_window.html.erb
- app/views/parks/show.html.erb
* fixed borders and spaces in park pop up
* fixed park show page design
> edited borders on pop up and redesigned park show page

- app/views/parks/show.html.erb
> seed image improved

- app/views/parks/show.html.erb
minor review btn fix park show
> minor review btn fix park show

- app/assets/stylesheets/components/_dogcard.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/pages/_index.scss
- app/javascript/controllers/chatroom_subscription_controller.js
- app/views/park_messages/index.html.erb
- app/views/parks/_dog_park.html.erb
did the icon 
fixed the bug on the chat
> icons+fixedbug

- app/assets/stylesheets/components/_dashboard.scss
> fixed dashboard pic size

- app/views/park_reviews/_review_form.html.erb
fixed button on review page to match other buttons
> fixed button on review page

- app/assets/stylesheets/components/_chat.scss
- app/views/park_messages/_message.html.erb
- app/views/park_messages/index.html.erb
- app/views/parks/_dog_park.html.erb
start the style of the chat page
> styleachatpage

- app/assets/stylesheets/components/_chat.scss
- app/assets/stylesheets/components/_dogcard.scss
- app/views/park_messages/_message.html.erb
- app/views/park_messages/index.html.erb
- app/views/parks/_dog_park.html.erb
finish the chat style and think in the dog park
> chat+dogcard

- app/views/parks/show.html.erb
- public/404.html
- public/500.html
back btn added on parks show
404 and 500 pages customized
> 404 and 500 pages includeed

- app/views/parks/_dog.html.erb
switched dog card in dashboard to have to dog card from park show page
> replaced dog card in dashboard

- app/assets/stylesheets/components/_dogcard.scss
circled dog image in it's card
> circled dog picture at the card

- app/assets/stylesheets/components/_dogcard.scss
- app/views/parks/_dog_park.html.erb
>  added nice hash next to trait
